"""DeepL and Whisper language code mappings."""

# Display name -> DeepL source language code
DEEPL_SOURCE_LANGUAGES: dict[str, str] = {
    "Auto-Detect": "",
    "Arabic": "AR",
    "Bulgarian": "BG",
    "Chinese": "ZH",
    "Czech": "CS",
    "Danish": "DA",
    "Dutch": "NL",
    "English": "EN",
    "Estonian": "ET",
    "Finnish": "FI",
    "French": "FR",
    "German": "DE",
    "Greek": "EL",
    "Hungarian": "HU",
    "Indonesian": "ID",
    "Italian": "IT",
    "Japanese": "JA",
    "Korean": "KO",
    "Latvian": "LV",
    "Lithuanian": "LT",
    "Norwegian": "NB",
    "Polish": "PL",
    "Portuguese": "PT",
    "Romanian": "RO",
    "Russian": "RU",
    "Slovak": "SK",
    "Slovenian": "SL",
    "Spanish": "ES",
    "Swedish": "SV",
    "Turkish": "TR",
    "Ukrainian": "UK",
}

# Display name -> DeepL target language code
DEEPL_TARGET_LANGUAGES: dict[str, str] = {
    "Arabic": "AR",
    "Bulgarian": "BG",
    "Chinese (Simplified)": "ZH-HANS",
    "Chinese (Traditional)": "ZH-HANT",
    "Czech": "CS",
    "Danish": "DA",
    "Dutch": "NL",
    "English (American)": "EN-US",
    "English (British)": "EN-GB",
    "Estonian": "ET",
    "Finnish": "FI",
    "French": "FR",
    "German": "DE",
    "Greek": "EL",
    "Hungarian": "HU",
    "Indonesian": "ID",
    "Italian": "IT",
    "Japanese": "JA",
    "Korean": "KO",
    "Latvian": "LV",
    "Lithuanian": "LT",
    "Norwegian": "NB",
    "Polish": "PL",
    "Portuguese (Brazilian)": "PT-BR",
    "Portuguese (European)": "PT-PT",
    "Romanian": "RO",
    "Russian": "RU",
    "Slovak": "SK",
    "Slovenian": "SL",
    "Spanish": "ES",
    "Swedish": "SV",
    "Turkish": "TR",
    "Ukrainian": "UK",
}

# DeepL language code -> Whisper language code
DEEPL_TO_WHISPER: dict[str, str] = {
    "AR": "ar",
    "BG": "bg",
    "ZH": "zh",
    "CS": "cs",
    "DA": "da",
    "NL": "nl",
    "EN": "en",
    "ET": "et",
    "FI": "fi",
    "FR": "fr",
    "DE": "de",
    "EL": "el",
    "HU": "hu",
    "ID": "id",
    "IT": "it",
    "JA": "ja",
    "KO": "ko",
    "LV": "lv",
    "LT": "lt",
    "NB": "no",
    "PL": "pl",
    "PT": "pt",
    "RO": "ro",
    "RU": "ru",
    "SK": "sk",
    "SL": "sl",
    "ES": "es",
    "SV": "sv",
    "TR": "tr",
    "UK": "uk",
}

# Whisper model sizes
WHISPER_MODELS: list[str] = ["tiny", "base", "small", "medium", "large"]

# DeepL to Google Translate language code mapping
DEEPL_TO_GOOGLE: dict[str, str] = {
    "AR": "ar",
    "BG": "bg",
    "ZH": "zh-cn",  # Google uses zh-cn for simplified
    "CS": "cs",
    "DA": "da",
    "NL": "nl",
    "EN": "en",
    "ET": "et",
    "FI": "fi",
    "FR": "fr",
    "DE": "de",
    "EL": "el",
    "HU": "hu",
    "ID": "id",
    "IT": "it",
    "JA": "ja",
    "KO": "ko",
    "LV": "lv",
    "LT": "lt",
    "NB": "no",
    "PL": "pl",
    "PT": "pt",
    "RO": "ro",
    "RU": "ru",
    "SK": "sk",
    "SL": "sl",
    "ES": "es",
    "SV": "sv",
    "TR": "tr",
    "UK": "uk",
}

# Translation services
TRANSLATION_SERVICES: dict[str, str] = {
    "DeepL (API Key Required)": "deepl",
    "Google Translate (Free)": "google",
}
